/**
 * TypeScript port of the abstracted heads-up NLHE game used to train the
 * Deep CFR strategy network (solver/poker_solver/games/holdem.py).
 *
 * Every rule and the feature encoding must match the Python engine
 * exactly -- the ONNX strategy network's outputs are only meaningful for
 * inputs encoded precisely as they were during training. Parity is
 * enforced by holdem.test.ts against vectors generated by the Python
 * engine (solver/scripts/gen_parity_vectors.py).
 *
 * Cards are ints 0..51: rank = card % 13 (0 = deuce .. 12 = ace),
 * suit = floor(card / 13). Chip unit = 0.5bb: stacks 200, blinds 1/2.
 * Player 0 = button/small blind (first to act preflop, second postflop).
 */

export type HistoryToken = number | string;
export type History = HistoryToken[];

export const FOLD = "f";
export const CHECK_CALL = "c";
export const ALL_IN = "a";
export const ACTION_ORDER = ["f", "c", "b0", "b1", "b2", "a"] as const;
export type ActionToken = (typeof ACTION_ORDER)[number];

const BET_FRACTIONS: Record<string, number> = { b0: 0.5, b1: 1.0, b2: 2.0 };
export const STACK = 200;
const SMALL_BLIND = 1;
const BIG_BLIND = 2;
const MAX_RAISES_PER_STREET = 3;
const NUM_STREETS = 4;
const BOARD_CARDS = [0, 3, 4, 5];

export const ACTION_INDEX: Record<string, number> = Object.fromEntries(
  ACTION_ORDER.map((a, i) => [a, i]),
);

export const FEATURE_DIM =
  52 + 52 + 4 + 3 + NUM_STREETS * 6 * ACTION_ORDER.length;
export const MAX_ACTIONS = ACTION_ORDER.length;

/** Python-compatible round-half-to-even (the trainer used Python round()). */
function bankersRound(x: number): number {
  const floor = Math.floor(x);
  const diff = x - floor;
  if (diff > 0.5) return floor + 1;
  if (diff < 0.5) return floor;
  return floor % 2 === 0 ? floor : floor + 1;
}

export type Status =
  | "chance_hole"
  | "act"
  | "chance_board"
  | "fold"
  | "showdown";

export interface ParsedState {
  status: Status;
  street: number;
  board: number[];
  contrib: [number, number];
  streetContrib: [number, number];
  acted: Set<number>;
  raises: number;
  lastIncrement: number;
  toAct: number;
  folder: number | null;
  /** Effective (per-player) stack for this hand, in 0.5bb units. */
  stack: number;
}

function firstToAct(street: number): number {
  return street === 0 ? 0 : 1;
}

function priorContrib(s: ParsedState, p: number): number {
  return s.contrib[p] - s.streetContrib[p];
}

/** Available aggressive tokens -> resulting street contribution. */
export function aggressiveAmounts(s: ParsedState): Record<string, number> {
  const p = s.toAct;
  const opp = 1 - p;
  const callAmount = s.streetContrib[opp];
  const stackLeft = s.stack - priorContrib(s, p);
  const potAfterCall = s.contrib[opp] + priorContrib(s, p) + callAmount;
  const minIncrement = Math.max(BIG_BLIND, s.lastIncrement);

  const out: Record<string, number> = {};
  if (s.raises < MAX_RAISES_PER_STREET) {
    let prevAmount = callAmount;
    for (const [token, frac] of Object.entries(BET_FRACTIONS)) {
      const increment = Math.max(
        bankersRound(frac * potAfterCall),
        minIncrement,
      );
      const amount = callAmount + increment;
      if (amount >= stackLeft) continue; // collapses into all-in
      if (amount <= prevAmount) continue; // duplicate/degenerate size
      out[token] = amount;
      prevAmount = amount;
    }
  }
  if (stackLeft > callAmount) {
    out[ALL_IN] = stackLeft;
  }
  return out;
}

export function parseHistory(h: History, stack: number = STACK): ParsedState {
  const s: ParsedState = {
    status: "chance_hole",
    street: 0,
    board: [],
    contrib: [SMALL_BLIND, BIG_BLIND],
    streetContrib: [SMALL_BLIND, BIG_BLIND],
    acted: new Set(),
    raises: 0,
    lastIncrement: BIG_BLIND,
    toAct: firstToAct(0),
    folder: null,
    stack,
  };
  if (h.length < 4) return s;

  const streetClosed = (): boolean => {
    if (s.streetContrib[0] !== s.streetContrib[1]) return false;
    return [0, 1].every((p) => s.acted.has(p) || s.contrib[p] >= s.stack);
  };

  let idx = 4;
  const n = h.length;
  for (;;) {
    let needed = BOARD_CARDS[s.street] - s.board.length;
    while (needed > 0 && idx < n) {
      s.board.push(h[idx] as number);
      idx += 1;
      needed -= 1;
    }
    if (needed > 0) {
      s.status = "chance_board";
      return s;
    }

    const bettingLive = [0, 1].every((p) => s.contrib[p] < s.stack);
    if (bettingLive) {
      let closed = false;
      while (idx < n && typeof h[idx] === "string") {
        const token = h[idx] as string;
        idx += 1;
        const p = s.toAct;
        const opp = 1 - p;
        s.acted.add(p);

        if (token === FOLD) {
          s.status = "fold";
          s.folder = p;
          return s;
        }
        const prior = priorContrib(s, p);
        if (token === CHECK_CALL) {
          s.streetContrib[p] = s.streetContrib[opp];
          s.contrib[p] = prior + s.streetContrib[p];
        } else {
          const amount = aggressiveAmounts(s)[token];
          s.lastIncrement = amount - s.streetContrib[opp];
          s.streetContrib[p] = amount;
          s.contrib[p] = prior + amount;
          s.raises += 1;
        }
        s.toAct = opp;
        if (streetClosed()) {
          closed = true;
          break;
        }
      }
      if (!closed) {
        if (idx >= n) {
          s.status = "act";
          return s;
        }
        throw new Error("board card appeared while betting still open");
      }
    }

    if (s.street === NUM_STREETS - 1) {
      s.status = "showdown";
      return s;
    }
    s.street += 1;
    s.streetContrib = [0, 0];
    s.acted = new Set();
    s.raises = 0;
    s.lastIncrement = BIG_BLIND;
    s.toAct = firstToAct(s.street);
  }
}

export function isChance(h: History, stack: number = STACK): boolean {
  const st = parseHistory(h, stack).status;
  return st === "chance_hole" || st === "chance_board";
}

export function isTerminal(h: History, stack: number = STACK): boolean {
  const st = parseHistory(h, stack).status;
  return st === "fold" || st === "showdown";
}

export function currentPlayer(h: History, stack: number = STACK): number {
  return parseHistory(h, stack).toAct;
}

export function legalActions(h: History, stack: number = STACK): string[] {
  const s = parseHistory(h, stack);
  const p = s.toAct;
  const facing = s.streetContrib[1 - p] > s.streetContrib[p];
  const actions: string[] = [];
  if (facing) actions.push(FOLD);
  actions.push(CHECK_CALL);
  actions.push(...Object.keys(aggressiveAmounts(s)));
  return actions;
}

export function legalActionIndices(
  h: History,
  stack: number = STACK,
): number[] {
  return legalActions(h, stack).map((a) => ACTION_INDEX[a]);
}

function actionsByStreet(h: History): string[][] {
  const out: string[][] = [[], [], [], []];
  let street = 0;
  let cardsSeen = 0;
  for (const x of h.slice(4)) {
    if (typeof x === "number") {
      cardsSeen += 1;
      if (cardsSeen === 3) street = 1;
      else if (cardsSeen === 4) street = 2;
      else if (cardsSeen === 5) street = 3;
    } else {
      out[street].push(x);
    }
  }
  return out;
}

/**
 * Suit-isomorphism canonicalization for feature encoding -- exact port of
 * `_canonical_suit_perm` in solver/poker_solver/games/holdem.py. Relabeling
 * suits never changes NLHE strategy, so we map the four suits to canonical
 * labels 0..3 by a rule depending only on the infoset's own cards (acting
 * player's hole + visible board). Each suit's signature is
 * (boardRankMask, holeRankMask); suits are ranked by that signature
 * (descending), tie-broken by original index. Returns perm where
 * perm[oldSuit] = canonicalSuit. Must stay bit-identical to the Python side.
 */
export function canonicalSuitPerm(hole: number[], board: number[]): number[] {
  const boardMask = [0, 0, 0, 0];
  const holeMask = [0, 0, 0, 0];
  for (const c of board) boardMask[Math.floor(c / 13)] |= 1 << (c % 13);
  for (const c of hole) holeMask[Math.floor(c / 13)] |= 1 << (c % 13);
  const order = [0, 1, 2, 3].sort((a, b) => {
    if (boardMask[a] !== boardMask[b]) return boardMask[b] - boardMask[a];
    if (holeMask[a] !== holeMask[b]) return holeMask[b] - holeMask[a];
    return a - b;
  });
  const perm = [0, 0, 0, 0];
  order.forEach((old, canonical) => {
    perm[old] = canonical;
  });
  return perm;
}

export function infosetFeatures(
  h: History,
  stack: number = STACK,
): Float32Array {
  const s = parseHistory(h, stack);
  const p = s.toAct;
  const x = new Float32Array(FEATURE_DIM);
  // Canonicalize suits (isomorphism) so flush structure is encoded
  // consistently across the four suit-symmetric variants of the spot.
  const hole = [h[2 * p] as number, h[2 * p + 1] as number];
  const perm = canonicalSuitPerm(hole, s.board);
  const canon = (c: number) => perm[Math.floor(c / 13)] * 13 + (c % 13);
  x[canon(hole[0])] = 1;
  x[canon(hole[1])] = 1;
  for (const c of s.board) x[52 + canon(c)] = 1;
  x[104 + s.street] = 1;
  const pot = s.contrib[0] + s.contrib[1];
  const toCall = s.streetContrib[1 - p] - s.streetContrib[p];
  x[108] = pot / (2 * s.stack);
  x[109] = toCall / s.stack;
  x[110] = (s.stack - s.contrib[p]) / s.stack;

  const base = 111;
  const streets = actionsByStreet(h);
  streets.forEach((acts, street) => {
    acts.slice(0, 6).forEach((a, slot) => {
      x[base + (street * 6 + slot) * ACTION_ORDER.length + ACTION_INDEX[a]] = 1;
    });
  });
  return x;
}

// ---- Showdown evaluation (port of solver hand_eval.py) ----

function straightHigh(rankSet: Set<number>): number | null {
  const ranks = new Set(rankSet);
  if (ranks.has(12)) ranks.add(-1);
  for (let high = 12; high >= 3; high--) {
    let ok = true;
    for (let i = 0; i < 5; i++) {
      if (!ranks.has(high - i)) {
        ok = false;
        break;
      }
    }
    if (ok) return high;
  }
  return null;
}

/** Orderable score array: compare lexicographically, higher = better. */
export function evaluate7(cards: number[]): number[] {
  const ranks = cards.map((c) => c % 13);
  const suits = cards.map((c) => Math.floor(c / 13));
  const rankCounts = new Map<number, number>();
  for (const r of ranks) rankCounts.set(r, (rankCounts.get(r) ?? 0) + 1);
  const suitCounts = new Map<number, number>();
  for (const s of suits) suitCounts.set(s, (suitCounts.get(s) ?? 0) + 1);

  let flushSuit: number | null = null;
  for (const [s, n] of suitCounts) {
    if (n >= 5) flushSuit = s;
  }
  let flushRanks: number[] = [];
  if (flushSuit !== null) {
    flushRanks = ranks
      .filter((_, i) => suits[i] === flushSuit)
      .sort((a, b) => b - a);
    const sfHigh = straightHigh(new Set(flushRanks));
    if (sfHigh !== null) return [8, sfHigh];
  }

  const byCount = [...rankCounts.entries()].sort(
    (a, b) => b[1] - a[1] || b[0] - a[0],
  );

  if (byCount[0][1] === 4) {
    const quad = byCount[0][0];
    const kicker = Math.max(...ranks.filter((r) => r !== quad));
    return [7, quad, kicker];
  }

  if (byCount[0][1] === 3) {
    const trips = byCount[0][0];
    const pairEntry = byCount.slice(1).find(([, n]) => n >= 2);
    if (pairEntry) return [6, trips, pairEntry[0]];
  }

  if (flushSuit !== null) return [5, ...flushRanks.slice(0, 5)];

  const straight = straightHigh(new Set(ranks));
  if (straight !== null) return [4, straight];

  if (byCount[0][1] === 3) {
    const trips = byCount[0][0];
    const kickers = ranks
      .filter((r) => r !== trips)
      .sort((a, b) => b - a)
      .slice(0, 2);
    return [3, trips, ...kickers];
  }

  if (byCount[0][1] === 2) {
    if (byCount[1][1] === 2) {
      const hi = byCount[0][0];
      const lo = byCount[1][0];
      const kicker = Math.max(...ranks.filter((r) => r !== hi && r !== lo));
      return [2, hi, lo, kicker];
    }
    const pair = byCount[0][0];
    const kickers = ranks
      .filter((r) => r !== pair)
      .sort((a, b) => b - a)
      .slice(0, 3);
    return [1, pair, ...kickers];
  }

  return [0, ...[...ranks].sort((a, b) => b - a).slice(0, 5)];
}

export function compareScores(a: number[], b: number[]): number {
  for (let i = 0; i < Math.max(a.length, b.length); i++) {
    const av = a[i] ?? -Infinity;
    const bv = b[i] ?? -Infinity;
    if (av !== bv) return av - bv;
  }
  return 0;
}

/** Terminal utilities in big blinds, (player0, player1). */
export function terminalReturns(
  h: History,
  stack: number = STACK,
): [number, number] {
  const s = parseHistory(h, stack);
  if (s.status === "fold") {
    const loser = s.folder as number;
    const lost = s.contrib[loser] / 2;
    return loser === 1 ? [lost, -lost] : [-lost, lost];
  }
  const board = s.board;
  const hand0 = evaluate7([h[0] as number, h[1] as number, ...board]);
  const hand1 = evaluate7([h[2] as number, h[3] as number, ...board]);
  const cmp = compareScores(hand0, hand1);
  if (cmp === 0) return [0, 0];
  const winner = cmp > 0 ? 0 : 1;
  const lost = s.contrib[1 - winner] / 2;
  return winner === 0 ? [lost, -lost] : [-lost, lost];
}
