/**
 * Cross-language parity: the TypeScript engine must reproduce the Python
 * training engine exactly on vectors generated by
 * solver/scripts/gen_parity_vectors.py. If any of this fails, the ONNX
 * strategy network is being fed inputs it was never trained on and every
 * probability in the tutor UI is garbage -- regenerate the vectors and
 * fix the port before shipping anything.
 */

import parity from "./parity-vectors.json";
import {
  FEATURE_DIM,
  type History,
  currentPlayer,
  infosetFeatures,
  isTerminal,
  legalActions,
  legalActionIndices,
  parseHistory,
  terminalReturns,
} from "./holdem";

type DecisionVector = {
  history: (number | string)[];
  player: number;
  legalActions: string[];
  legalIndices: number[];
  street: number;
  pot: number;
  toCall: number;
  features: Record<string, number>;
};

type TerminalVector = {
  history: (number | string)[];
  terminalReturns: [number, number];
};

const vectors = parity.vectors as (DecisionVector | TerminalVector)[];
const decisionVectors = vectors.filter(
  (v): v is DecisionVector => "features" in v,
);
const terminalVectors = vectors.filter(
  (v): v is TerminalVector => "terminalReturns" in v,
);

describe("holdem TS/Python parity", () => {
  it("has matching feature dimension", () => {
    expect(FEATURE_DIM).toBe(parity.featureDim);
  });

  it("covers a meaningful number of vectors", () => {
    expect(decisionVectors.length).toBeGreaterThan(200);
    expect(terminalVectors.length).toBeGreaterThan(20);
  });

  it("matches player to act, legal actions, and canonical indices", () => {
    for (const v of decisionVectors) {
      expect(currentPlayer(v.history)).toBe(v.player);
      expect(legalActions(v.history)).toEqual(v.legalActions);
      expect(legalActionIndices(v.history)).toEqual(v.legalIndices);
    }
  });

  it("matches street, pot, and to-call accounting", () => {
    for (const v of decisionVectors) {
      const s = parseHistory(v.history);
      expect(s.street).toBe(v.street);
      expect(s.contrib[0] + s.contrib[1]).toBe(v.pot);
      expect(s.streetContrib[1 - s.toAct] - s.streetContrib[s.toAct]).toBe(
        v.toCall,
      );
    }
  });

  it("matches the feature encoding exactly", () => {
    for (const v of decisionVectors) {
      const feats = infosetFeatures(v.history);
      const nonzero: Record<string, number> = {};
      feats.forEach((val, i) => {
        if (val !== 0) nonzero[String(i)] = Math.round(val * 1e6) / 1e6;
      });
      expect(nonzero).toEqual(v.features);
    }
  });

  it("matches terminal payouts (fold and showdown)", () => {
    for (const v of terminalVectors) {
      expect(isTerminal(v.history)).toBe(true);
      const r = terminalReturns(v.history);
      expect(r[0]).toBeCloseTo(v.terminalReturns[0], 9);
      expect(r[1]).toBeCloseTo(v.terminalReturns[1], 9);
    }
  });
});

// Suit-isomorphism canonicalization -- mirrors the Python tests
// test_infoset_features_are_suit_isomorphism_invariant and
// test_flush_relevance_is_preserved_after_canonicalization. Model-free.

function permutations4(): number[][] {
  const out: number[][] = [];
  const perm: number[] = [];
  const used = [false, false, false, false];
  const rec = () => {
    if (perm.length === 4) {
      out.push([...perm]);
      return;
    }
    for (let s = 0; s < 4; s++) {
      if (used[s]) continue;
      used[s] = true;
      perm.push(s);
      rec();
      perm.pop();
      used[s] = false;
    }
  };
  rec();
  return out;
}

function permuteSuits(h: History, perm: number[]): History {
  return h.map((c) =>
    typeof c === "number" ? perm[Math.floor(c / 13)] * 13 + (c % 13) : c,
  );
}

describe("holdem suit canonicalization", () => {
  const PERMS = permutations4();

  it("encodes suit-permuted spots identically (isomorphism invariance)", () => {
    // Use the parity decision vectors as a bank of real reachable nodes.
    for (const v of decisionVectors) {
      const base = infosetFeatures(v.history);
      for (const perm of PERMS) {
        const permuted = permuteSuits(v.history, perm);
        expect(Array.from(infosetFeatures(permuted))).toEqual(Array.from(base));
        expect(legalActions(permuted)).toEqual(legalActions(v.history));
      }
    }
  });

  it("still distinguishes flush-relevant from irrelevant hands", () => {
    // Flop decision for P1 after limp/check on a two-tone (club) flop.
    const board = [0, 8, 16]; // 2c, Tc, 5d
    const villain = [39, 40]; // 2s, 3s (never enter P1 features)
    const flop = (hole: number[]): History => [
      villain[0],
      villain[1],
      hole[0],
      hole[1],
      "c",
      "c",
      ...board,
    ];
    const draw = infosetFeatures(flop([12, 10])); // Ac Qc -- nut flush draw
    const brick = infosetFeatures(flop([38, 36])); // Ah Qh -- same ranks, no club
    expect(Array.from(draw)).not.toEqual(Array.from(brick));
  });
});
