/**
 * Cross-language parity: the TypeScript engine must reproduce the Python
 * training engine exactly on vectors generated by
 * solver/scripts/gen_parity_vectors.py. If any of this fails, the ONNX
 * strategy network is being fed inputs it was never trained on and every
 * probability in the tutor UI is garbage -- regenerate the vectors and
 * fix the port before shipping anything.
 */

import parity from "./parity-vectors.json";
import {
  FEATURE_DIM,
  currentPlayer,
  infosetFeatures,
  isTerminal,
  legalActions,
  legalActionIndices,
  parseHistory,
  terminalReturns,
} from "./holdem";

type DecisionVector = {
  history: (number | string)[];
  player: number;
  legalActions: string[];
  legalIndices: number[];
  street: number;
  pot: number;
  toCall: number;
  features: Record<string, number>;
};

type TerminalVector = {
  history: (number | string)[];
  terminalReturns: [number, number];
};

const vectors = parity.vectors as (DecisionVector | TerminalVector)[];
const decisionVectors = vectors.filter(
  (v): v is DecisionVector => "features" in v,
);
const terminalVectors = vectors.filter(
  (v): v is TerminalVector => "terminalReturns" in v,
);

describe("holdem TS/Python parity", () => {
  it("has matching feature dimension", () => {
    expect(FEATURE_DIM).toBe(parity.featureDim);
  });

  it("covers a meaningful number of vectors", () => {
    expect(decisionVectors.length).toBeGreaterThan(200);
    expect(terminalVectors.length).toBeGreaterThan(20);
  });

  it("matches player to act, legal actions, and canonical indices", () => {
    for (const v of decisionVectors) {
      expect(currentPlayer(v.history)).toBe(v.player);
      expect(legalActions(v.history)).toEqual(v.legalActions);
      expect(legalActionIndices(v.history)).toEqual(v.legalIndices);
    }
  });

  it("matches street, pot, and to-call accounting", () => {
    for (const v of decisionVectors) {
      const s = parseHistory(v.history);
      expect(s.street).toBe(v.street);
      expect(s.contrib[0] + s.contrib[1]).toBe(v.pot);
      expect(s.streetContrib[1 - s.toAct] - s.streetContrib[s.toAct]).toBe(
        v.toCall,
      );
    }
  });

  it("matches the feature encoding exactly", () => {
    for (const v of decisionVectors) {
      const feats = infosetFeatures(v.history);
      const nonzero: Record<string, number> = {};
      feats.forEach((val, i) => {
        if (val !== 0) nonzero[String(i)] = Math.round(val * 1e6) / 1e6;
      });
      expect(nonzero).toEqual(v.features);
    }
  });

  it("matches terminal payouts (fold and showdown)", () => {
    for (const v of terminalVectors) {
      expect(isTerminal(v.history)).toBe(true);
      const r = terminalReturns(v.history);
      expect(r[0]).toBeCloseTo(v.terminalReturns[0], 9);
      expect(r[1]).toBeCloseTo(v.terminalReturns[1], 9);
    }
  });
});
